---
- name: Docker | Create keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Docker | Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Docker | Add Docker repository
  copy:
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/debian
      Suites: {{ ansible_distribution_release | lower }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc
    dest: /etc/apt/sources.list.d/docker.sources
    mode: '0644'

- name: Docker | Update apt cache after adding repository
  apt:
    update_cache: yes

- name: Docker | Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Docker | Check Docker version
  command: docker --version
  register: docker_version
  changed_when: false

- name: Docker | Show version
  debug:
    msg: "Docker {{ docker_version.stdout }} successfully installed"
